### ISSUE TITLE
Windows Defender just detected tojan

### ISSUE THREAD

**Issue by Grandorg** [Sevii77/aetherment#7] opened 2024-12-22 03:20 UTC
After i restarted my Game Windows Defender got very angry at me and detected a severe Threat in the Aetherment_core.dll file as a Tojan. I hope that is a false alarm from it.
![ApplicationFrameHost_haCSEmz2Hx](https://github.com/user-attachments/assets/3c98c9df-9f7f-4143-a74f-6b4e6e5a1b81)

**Comment by Sevii77** [comment] 2024-12-22 03:27
Duplicate of #6. But yes, it's a false positive and ACT suffers from the same problem (https://github.com/ravahn/FFXIV_ACT_Plugin/issues/324). Aetherment uses the same rust crate `retour`

**Closed by Sevii77** 2024-12-22 03:27 UTC
