### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'Aetherment.Native' threw an exception.

### ISSUE THREAD

**Issue by LosDrakakos** [Sevii77/aetherment#8] opened 2024-12-24 12:20 UTC
Hi,
 after a fresh install of both my OS and FFXIV, I get this error when enabling Aetherment.

```
13:04:11.126 | FTL | [Aetherment] System.TypeInitializationException: The type initializer for 'Aetherment.Native' threw an exception.
		 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'handle')
		   at System.ArgumentNullException.Throw(String paramName)
		   at System.Runtime.InteropServices.NativeLibrary.GetExport(IntPtr handle, String name)
		   at Aetherment.Native..cctor()
		   --- End of inner exception stack trace ---
		   at Aetherment.Aetherment..ctor()

```

I'm running
Fedora Silverblue 41
Aetherment 0.1.17.0 
Release branch of Dalamud (2024.12.07.0000.0000)

I tried removing/reinstalling the plugin, deleting my .xlcore folder and reinstalling everything, same result.

Am I missing a dependency or something?

**Comment by Sevii77** [comment] 2024-12-24 12:55
duplicate of #4, Aetherment currently doesn't work on linux out of the box. You can try the steps posted there or copying the file from another location, it worked for me during testing but didn't for others so your milage may vary.

**Closed by Sevii77** 2024-12-24 12:55 UTC
